# Generated by Django 5.1.6 on 2025-04-13 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id_dokter', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_dokter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id_rumah_sakit', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_rumah_sakit', models.CharField(max_length=100, unique=True)),
                ('alamat_rumah_sakit', models.TextField()),
                ('no_telp', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalKonsultasi',
            fields=[
                ('id_jdwl_konsultasi', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hari', models.CharField(max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('kuota', models.PositiveIntegerField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_konsultasi', to='book_konsultasi.dokter')),
            ],
            options={
                'unique_together': {('dokter', 'hari', 'jam_mulai')},
            },
        ),
        migrations.CreateModel(
            name='BookKonsultasi',
            fields=[
                ('id_book_konsultasi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_pasien', models.UUIDField()),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_konsultasi.jadwalkonsultasi')),
            ],
        ),
        migrations.AddField(
            model_name='dokter',
            name='rumah_sakit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokter', to='book_konsultasi.rumahsakit'),
        ),
    ]
