# Generated by Django 5.1.6 on 2025-04-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_konsultasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalkonsultasi',
            name='dokter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_konsultasi', to='book_konsultasi.dokter'),
        ),
    ]
