services:
  db-main:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my-network  

  django-main:
    build: .
    container_name: django-main
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - db-main
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DB_ENGINE}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_main_data:

networks:
  my-network:
    external: true
