apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGN6T1RFMQpPREkxTURBZUZ3MHlOVEF5TVRBd016TXdOVEJhRncwek5UQXlNRGd3TXpNd05UQmFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56TTVNVFU0TWpVd01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUdLSmZKVldqSHhPRgpVQkUwV3VyUWhFWDUvZ0pIQVZpMFNHL1Vtb2JaWFYyTmM1UXYwNFgwVGZBRzVZSk9CVFlja0puNHIzcFFQVGVzCmlhRjR0azE1eXFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGRUVod2lIZ0pkbW1XQmZJMW84emlKdWxPRTZMTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEUQpYVVFVekZnTDV3cDlDdEhxQnV1ZHhlNVA2Tzhhay9rT3NLeE96MjhJWHdJaEFMNlo2OFdiMjYvRTR1NGJkclJtCndxMm80Vk81cGpQMjVIaEVCU2pMRzNHOAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://localhost:8443/k8s/clusters/c-m-hx88nxj9
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: kelompok-38-ns
    user: kelompok-38
  name: kelompok-38-context
current-context: kelompok-38-context
kind: Config
preferences: {}
users:
- name: kelompok-38
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1KYjRkM21CaFJGeVd2R0FFc2NSZVl4WmVlcllFX1BSMktsaGpNc2taOEkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrZWxvbXBvay0zOC1ucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrZWxvbXBvay0zOC1ucy1zYS1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoia2Vsb21wb2stMzgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI1YzczYzQwZi0wMjk3LTRhYTQtODhhMi03YTQ3NTQ2NTZkMWQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a2Vsb21wb2stMzgtbnM6a2Vsb21wb2stMzgifQ.PC5Hginhf73v1NUql_RPmC0hpDj_7mdDNgus9Zk4IcdSFuMy6iLXzYO6-sTHXP4vXQn2W1vSl0c3SuubjX7i1NP1R7tSZVzP9T5ineYHeNcYrWDqsD7gY49BLaJ781hW2ENO739XVzY54fn4PkVA4u3a0MHBj9sSQj19sAUsr_lH9P2f9E2bCidOckWajzzDdZTWSaYnojjcfqEV6sw10hbiEb_AY5u0eFM5P2lveJw3YLTr-2uZYi1av47hldi0mlhbwt3z15iElbouT8RO3l2Jhv-arJ6CuTvTHSaZceoBLTKny-SVHwEnvz3-mVlAth0tLG2l0gSF5E8wW4tISQ
