POST http://127.0.0.1:8000/register
Content-Type: application/json

{ "username": "adam2", "password": "Pass1234!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "adam2", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test-token 
Content-Type: application/json
Authorization: token 7c354eb33c826a79f8c062432e94a4265b18bf44