variables:
  # App Specifications
  MIN_CPU: 83m
  MIN_MEMORY: 170Mi
  MAX_CPU: 333m
  MAX_MEMORY: 341Mi
  PORT: 80

  # Image and Deployment Variables, It's better to not change these variables below
  # because they are used in the deploy script
  VERSION: $CI_COMMIT_TAG
  TAG_IMAGE_NAME: "$registry_host/$CI_PROJECT_PATH:$VERSION"
  APP_NAME: "$CI_PROJECT_NAME"
  INGRESS_HOST: "$CI_PROJECT_PATH_SLUG"

  # App Variables, you can add your own variables here
  # App variables must have the prefix "PODS_"
  PODS_TEST: tests
  PODS_KUBECONFIG: $KUBECONFIG
  PODS_DB_HOST: $DB_HOST
  PODS_DB_NAME: $DB_NAME
  PODS_DB_PASSWORD: $DB_PASSWORD
  PODS_DB_PORT: $DB_PORT
  PODS_DB_USERNAME: $DB_USERNAME
  PODS_DB_ENGINE: $DB_ENGINE
  PODS_DJANGO_CSRF_TRUSTED_ORIGINS: $DJANGO_CSRF_TRUSTED_ORIGINS
  PODS_DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
  PODS_DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
  PODS_DEBUG: $DEBUG
