# Generated by Django 5.1.6 on 2025-04-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_konsultasi', '0002_alter_jadwalkonsultasi_dokter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dokter', models.UUIDField()),
                ('nama_dokter', models.CharField(max_length=100)),
                ('kuota', models.PositiveIntegerField()),
                ('rumah_sakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_konsultasi.rumahsakit')),
            ],
        ),
    ]
