# Generated by Django 5.1.6 on 2025-04-13 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id_dokter', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_dokter', models.CharField(max_length=100)),
                ('kuota', models.PositiveIntegerField()),
            ],
        ),
    ]
