# Generated by Django 5.1.6 on 2025-04-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_kuota', '0002_jadwalkonsultasi_delete_dokter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JadwalKonsultasi',
        ),
    ]
