# Generated by Django 5.1.6 on 2025-02-11 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_rumah_sakit', models.CharField(max_length=25)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'Rumah Sakit',
            },
        ),
    ]
