# Generated by Django 5.1.6 on 2025-02-11 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id_dokter', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_dokter', models.CharField(max_length=40)),
                ('rumah_sakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rumahsakit')),
            ],
        ),
    ]
