# Generated by Django 5.1.6 on 2025-02-11 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dokter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hari', models.CharField(max_length=10)),
                ('jam', models.CharField(max_length=20)),
                ('kuota', models.IntegerField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dokter')),
            ],
        ),
    ]
