# Generated by Django 5.1.6 on 2025-02-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jadwal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='rumah_sakit',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='dokter',
        ),
        migrations.DeleteModel(
            name='RumahSakit',
        ),
        migrations.DeleteModel(
            name='Dokter',
        ),
        migrations.DeleteModel(
            name='Jadwal',
        ),
    ]
