# Generated by Django 5.1.6 on 2025-04-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_remove_dokter_rumah_sakit_remove_jadwal_dokter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(max_length=500)),
                ('title_style', models.CharField(choices=[('default', 'Gaya Default'), ('red-shadow', 'Bayangan Merah')], default='default', max_length=20)),
                ('primary_color', models.CharField(default='#c62828', max_length=7)),
                ('secondary_color', models.CharField(default='#e53935', max_length=7)),
                ('bg_color', models.CharField(default='#ffebee', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('section_type', models.CharField(choices=[('normal', 'Normal'), ('red', 'Section Merah'), ('white', 'Section Putih'), ('special', 'Special Content')], default='normal', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('has_list', models.BooleanField(default=False)),
                ('has_highlight', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
