# Generated by Django 5.1.6 on 2025-04-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='article',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_style',
        ),
        migrations.DeleteModel(
            name='ArticleSection',
        ),
    ]
