# Generated by Django 5.1.6 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
                ('deskripsi', models.TextField()),
                ('aturan_pakai', models.TextField()),
                ('stok', models.FloatField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='obat/')),
                ('kategori', models.CharField(default='kardiovaskular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
