# Generated by Django 5.1.6 on 2025-03-28 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_obat', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField(max_length=1000)),
                ('aturan_pakai', models.TextField(max_length=1000)),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
