# Generated by Django 5.1.6 on 2025-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField(max_length=1000)),
                ('aturan_pakai', models.TextField(max_length=1000)),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
