# Generated by Django 5.1.6 on 2025-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obat',
            options={'ordering': ['-tanggal_dibuat']},
        ),
        migrations.RenameField(
            model_name='obat',
            old_name='created_at',
            new_name='tanggal_dibuat',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='aturan_pakai',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='obat',
            name='kandungan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='obat',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='obat',
            name='kategori',
            field=models.CharField(choices=[('Antihipertensi', 'Antihipertensi'), ('Antikoagulan', 'Antikoagulan'), ('Antiaritmia', 'Antiaritmia'), ('Kolesterol', 'Kolesterol'), ('Suplemen Jantung', 'Suplemen Jantung')], max_length=50),
        ),
        migrations.AlterField(
            model_name='obat',
            name='nama_obat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obat',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
