# Generated by Django 5.1.6 on 2025-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipembelianobat',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
