# Generated by Django 5.1.6 on 2025-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='aturan_pakai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
