# Generated by Django 5.1.6 on 2025-04-01 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPembelianObat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu_transaksi', models.DateTimeField(auto_now_add=True)),
                ('total_biaya', models.IntegerField()),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='beli_obat.obat', verbose_name='Obat yang dibeli')),
            ],
        ),
    ]
