# Generated by Django 5.1.6 on 2025-04-07 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
