# Generated by Django 5.1.6 on 2025-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0002_alter_obat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obat',
            options={'verbose_name': 'Obat', 'verbose_name_plural': 'Obat'},
        ),
        migrations.RemoveField(
            model_name='obat',
            name='kandungan',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='tanggal_dibuat',
        ),
        migrations.AddField(
            model_name='obat',
            name='aturan_pakai',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
