# Generated by Django 5.1.6 on 2025-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0002_transaksipembelianobat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipembelianobat',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
