# Generated by Django 5.1.6 on 2025-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_obat', '0003_alter_obat_options_remove_obat_kandungan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='aturan_pakai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
